version: '3'
services:
  mysql:
    image: mysql:latest
    #   restart: no
    restart: always
    environment:
      #    MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: planner
    #   MYSQL_USER: user
    #  MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    volumes:
      # - C:\xampp\mysql\data\planner:/path/to/mysql_data
      # - C:\xampp\mysql\data\planner:/var/lib/mysql
      - mysql_data:/var/lib/mysql  # Šitas veikia visi kiti ne
    # - /c/xampp/mysql/data/planner
    #  - /c/xampp/mysql/data/planner:/var/lib/mysql
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://planner-mysql-1:3306/planner?useSSL=false
     # SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/planner?useSSL=false
     # url: jdbc:mysql://host.docker.internal:3306/planner?useSSL=false
    depends_on:
      - mysql
volumes:
  mysql_data:
