server:
  port: 8080
  #error:
  #include-message: always
  #  include-exception: true
error:
  handling:
    http-status-in-json-response: true
    include-message: always
    include-exception: true
    # include-stacktrace: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/planner?useSSL=false
    # url: jdbc:mysql://planner-mysql-1:3306/planner?useSSL=false     # Šitas veikia taip pat kaip ir viršutinis
    #url: jdbc:mysql://host.docker.internal:3306/planner?useSSL=false  # taip bandžiau pasiekti kompo db, nepavyko
    # username: root
    # password:

    username: root
    password:

  jpa:
    hibernate:
    ddl-auto: update
    #  ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
