server:
  port: 8080

  #error:
    #include-message: always
  #  include-exception: true
error:
  handling:
    http-status-in-json-response: true
    include-message: always
    include-exception: true
   # include-stacktrace: always
spring:
  datasource:
  #  url: jdbc:mysql://localhost:3306/planner?useSSL=false
    # username: root
    # password:

  #  url: jdbc:mysql://planner-mysql-1:3307/planner?useSSL=false

    url: jdbc:mysql://planner-mysql-1:3306/planner?useSSL=false
    username: root
    password:

# JPA Settings
 # jpa.hibernate.ddl_auto: update

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect